-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  contact_info text, -- WhatsApp or Phone number. NO internal chat.
  email text, -- Added for public visibility control or display
  avatar_url text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS) for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for items
create table items (
  id bigint generated by default as identity primary key,
  seller_id uuid references auth.users not null,
  title text not null,
  description text,
  price decimal(10, 2) not null,
  category text not null,
  image_url text, -- URL from Storage
  status text default 'active' check (status in ('active', 'sold', 'hidden')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for items
alter table items enable row level security;

create policy "Items are viewable by everyone."
  on items for select
  using ( true );

create policy "Authenticated users can insert their own items."
  on items for insert
  with check ( auth.uid() = seller_id );

create policy "Users can update their own items."
  on items for update
  using ( auth.uid() = seller_id );
  
-- Storage Bucket Policies (Note: Buckets must be created in the Storage UI first, or via extension if available)
-- Assuming a bucket named 'item-images' exists.

-- Policy to allow public read access to the 'item-images' bucket
-- This SQL command usually runs against the storage.objects table but creating buckets via SQL is specific.
-- Below are policies for objects within the bucket.

-- Enable RLS on storage.objects if not already enabled (it usually is)
-- alter table storage.objects enable row level security;

-- Policy: Allow Public Read
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'item-images' );

-- Policy: Allow Authenticated Uploads
create policy "Authenticated users can upload images"
on storage.objects for insert
with check (
  bucket_id = 'item-images' and
  auth.role() = 'authenticated'
);

-- Policy: Allow Public Read for avatars
create policy "Public Access Avatars"
on storage.objects for select
using ( bucket_id = 'avatars' );

-- Policy: Allow Authenticated Uploads for avatars
create policy "Authenticated users can upload avatars"
on storage.objects for insert
with check (
  bucket_id = 'avatars' and
  auth.role() = 'authenticated'
);
